"""Added threshold field to Image

Revision ID: 01a5ed942e84
Revises: 1c363fa5258e
Create Date: 2024-05-14 12:18:12.357182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a5ed942e84'
down_revision: Union[str, None] = '1c363fa5258e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Image', sa.Column('threshold', sa.Float(), nullable=False))
    op.create_index(op.f('ix_Image_threshold'), 'Image', ['threshold'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Image_threshold'), table_name='Image')
    op.drop_column('Image', 'threshold')
    # ### end Alembic commands ###
