"""refactored model's relations

Revision ID: 1c363fa5258e
Revises: 47b19418305b
Create Date: 2024-04-23 22:38:43.455851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c363fa5258e'
down_revision: Union[str, None] = '47b19418305b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CommentLikes', sa.Column('comment_id', sa.Integer(), nullable=False))
    op.add_column('CommentLikes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('CommentLikes_Comment_fkey', 'CommentLikes', type_='foreignkey')
    op.drop_constraint('CommentLikes_User_fkey', 'CommentLikes', type_='foreignkey')
    op.create_foreign_key('comment_likes_user_id', 'CommentLikes', 'User', ['user_id'], ['id'])
    op.create_foreign_key('comment_likes_comment_id', 'CommentLikes', 'Comment', ['comment_id'], ['id'])
    op.drop_column('CommentLikes', 'User')
    op.drop_column('CommentLikes', 'Comment')
    op.add_column('ImageLikes', sa.Column('image_id', sa.Integer(), nullable=False))
    op.add_column('ImageLikes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('ImageLikes_User_fkey', 'ImageLikes', type_='foreignkey')
    op.drop_constraint('ImageLikes_Image_fkey', 'ImageLikes', type_='foreignkey')
    op.create_foreign_key('image_likes_image_id', 'ImageLikes', 'Image', ['image_id'], ['id'])
    op.create_foreign_key('image_likes_user_id', 'ImageLikes', 'User', ['user_id'], ['id'])
    op.drop_column('ImageLikes', 'Image')
    op.drop_column('ImageLikes', 'User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImageLikes', sa.Column('User', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ImageLikes', sa.Column('Image', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('image_likes_user_id', 'ImageLikes', type_='foreignkey')
    op.drop_constraint('image_likes_image_id', 'ImageLikes', type_='foreignkey')
    op.create_foreign_key('ImageLikes_Image_fkey', 'ImageLikes', 'Image', ['Image'], ['id'])
    op.create_foreign_key('ImageLikes_User_fkey', 'ImageLikes', 'User', ['User'], ['id'])
    op.drop_column('ImageLikes', 'user_id')
    op.drop_column('ImageLikes', 'image_id')
    op.add_column('CommentLikes', sa.Column('Comment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('CommentLikes', sa.Column('User', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('comment_likes_comment_id', 'CommentLikes', type_='foreignkey')
    op.drop_constraint('comment_likes_user_id', 'CommentLikes', type_='foreignkey')
    op.create_foreign_key('CommentLikes_User_fkey', 'CommentLikes', 'User', ['User'], ['id'])
    op.create_foreign_key('CommentLikes_Comment_fkey', 'CommentLikes', 'Comment', ['Comment'], ['id'])
    op.drop_column('CommentLikes', 'user_id')
    op.drop_column('CommentLikes', 'comment_id')
    # ### end Alembic commands ###
