"""fixing typo in Image: coordinates_classes attribute

Revision ID: 47b19418305b
Revises: ce67f068225c
Create Date: 2024-04-20 14:25:01.138174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47b19418305b'
down_revision: Union[str, None] = 'ce67f068225c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Image', sa.Column('coordinates_classes', sa.JSON(), nullable=True))
    op.drop_column('Image', 'coordintes_classes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Image', sa.Column('coordintes_classes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('Image', 'coordinates_classes')
    # ### end Alembic commands ###
