"""removed image likes

Revision ID: 6c6d256a5a51
Revises: e45bc2bc47e8
Create Date: 2024-06-07 12:28:02.368440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6d256a5a51'
down_revision: Union[str, None] = 'e45bc2bc47e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ImageLikes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ImageLikes',
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['Image.id'], name='image_likes_image_id'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='image_likes_user_id')
    )
    # ### end Alembic commands ###
