"""Fixed relationship between comment and tag

Revision ID: e45bc2bc47e8
Revises: 544b22ea495f
Create Date: 2024-05-24 17:13:02.631909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45bc2bc47e8'
down_revision: Union[str, None] = '544b22ea495f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Comment_tag_id_fkey', 'Comment', type_='foreignkey')
    op.drop_column('Comment', 'tag_id')
    op.add_column('Tag', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Tag', 'Comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tag', type_='foreignkey')
    op.drop_column('Tag', 'comment_id')
    op.add_column('Comment', sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Comment_tag_id_fkey', 'Comment', 'Tag', ['tag_id'], ['id'])
    # ### end Alembic commands ###
