name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  qodana-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: Skip the backend scan
        id: skip-scan
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["backend/**"]'
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        timeout-minutes: 20
        with:
          # https://github.com/jetbrains/qodana-cli#options-1
          args: --project-dir,backend,--baseline,qodana.sarif.json
          results-dir: ${{ runner.temp }}/qodana/results-backend
          artifact-name: qodana-report-backend
          cache-dir: ${{ runner.temp }}/qodana/caches-backend
          additional-cache-hash: ${{ github.sha }}-backend
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

  qodana-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: Skip the frontend scan
        id: skip-scan
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["frontend/**"]'
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        timeout-minutes: 20
        with:
          # https://github.com/jetbrains/qodana-cli#options-1
          args: --project-dir,frontend,--baseline,qodana.sarif.json
          results-dir: ${{ runner.temp }}/qodana/results-frontend
          artifact-name: qodana-report-frontend
          cache-dir: ${{ runner.temp }}/qodana/caches-frontend
          additional-cache-hash: ${{ github.sha }}-frontend
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
